name: Windows build

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Clone skMHL-avs dependency
        run: |
          git clone https://github.com/shadowlmd/skMHL-avs.git

      - name: Cache FPC
        uses: actions/cache@v3
        with:
          path: C:\FPC\3.2.2
          key: fpc-3.2.2

      - name: Download and install FreePascal if not cached
        shell: powershell
        run: |
          if (!(Test-Path "C:\FPC\3.2.2\fpc.exe")) {
              $url = "http://downloads.freepascal.org/fpc/dist/3.2.2/i386-win32/fpc-3.2.2.i386-win32.exe"
              Invoke-WebRequest -Uri $url -OutFile fpc-installer.exe
              Start-Process -FilePath .\fpc-installer.exe -ArgumentList '/VERYSILENT', 'INSTALLDIR=C:\FPC\3.2.2' -Wait
          }

      - name: Build mbtool (Release)
        shell: cmd
        run: |
          mkdir release
          C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -dRELEASE ^
            -Flrelease ^
            -FUrelease ^
            -FuskMHL-avs\sources ^
            -FiskMHL-avs\sources ^
            -g -gl ^
            mbtool.pas
          dir release

      - name: Create ZIP archive
        shell: powershell
        run: |
          dir
          dir release
          Compress-Archive -Path release\mbtool.exe -DestinationPath mbtool-windows.zip

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: mbtool-windows
          path: mbtool-windows.zip
