name: Windows build

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Clone skMHL-avs dependency
        run: |
          git clone https://github.com/shadowlmd/skMHL-avs.git

      - name: Cache FreePascal
        uses: actions/cache@v3
        with:
          path: C:\FPC\3.2.2
          key: fpc-3.2.2

      - name: Download and install FreePascal
        shell: powershell
        run: |
          if (!(Test-Path "C:\FPC\3.2.2\bin\i386-win32\fpc.exe")) {
              $url = "http://downloads.freepascal.org/fpc/dist/3.2.2/i386-win32/fpc-3.2.2.i386-win32.exe"
              Invoke-WebRequest -Uri $url -OutFile fpc-installer.exe
              Start-Process -FilePath .\fpc-installer.exe -ArgumentList '/VERYSILENT' -Wait
          }

      - name: Build mbtool.exe
        shell: cmd
        run: |
          mkdir release
          C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -dRELEASE ^
            -Flrelease ^
            -FUrelease ^
            -FuskMHL-avs\sources ^
            -FiskMHL-avs\sources ^
            -g -gl ^
            mbtool.pas

      - name: Create archive
        shell: powershell
        run: |
          Compress-Archive -Path mbtool.exe -DestinationPath mbtool-windows.zip

      - name: Move latest tag to current commit
        shell: powershell
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag --force latest
          git push --force origin latest

      - name: GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: latest
          tag: latest
          allowUpdates: true
          artifacts: mbtool-windows.zip
          replacesArtifacts: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
